System.register([], function (exports_1, context_1) {
    "use strict";
    var A1, A2, A3, A4, A5, A6, A7, A8, B1, B2, B3, B4, B5, B6, B7, B8, C1, C2, C3, C4, C5, C6, C7, C8, D1, D2, D3, D4, D5, D6, D7, D8, E1, E2, E3, E4, E5, E6, E7, E8, F1, F2, F3, F4, F5, F6, F7, F8, G1, G2, G3, G4, G5, G6, G7, G8, H1, H2, H3, H4, H5, H6, H7, H8;
    var __moduleName = context_1 && context_1.id;
    return {
        setters: [],
        execute: function () {
            exports_1("A1", A1 = Object.freeze([0, 0]));
            exports_1("A2", A2 = Object.freeze([0, 1]));
            exports_1("A3", A3 = Object.freeze([0, 2]));
            exports_1("A4", A4 = Object.freeze([0, 3]));
            exports_1("A5", A5 = Object.freeze([0, 4]));
            exports_1("A6", A6 = Object.freeze([0, 5]));
            exports_1("A7", A7 = Object.freeze([0, 6]));
            exports_1("A8", A8 = Object.freeze([0, 7]));
            exports_1("B1", B1 = Object.freeze([1, 0]));
            exports_1("B2", B2 = Object.freeze([1, 1]));
            exports_1("B3", B3 = Object.freeze([1, 2]));
            exports_1("B4", B4 = Object.freeze([1, 3]));
            exports_1("B5", B5 = Object.freeze([1, 4]));
            exports_1("B6", B6 = Object.freeze([1, 5]));
            exports_1("B7", B7 = Object.freeze([1, 6]));
            exports_1("B8", B8 = Object.freeze([1, 7]));
            exports_1("C1", C1 = Object.freeze([2, 0]));
            exports_1("C2", C2 = Object.freeze([2, 1]));
            exports_1("C3", C3 = Object.freeze([2, 2]));
            exports_1("C4", C4 = Object.freeze([2, 3]));
            exports_1("C5", C5 = Object.freeze([2, 4]));
            exports_1("C6", C6 = Object.freeze([2, 5]));
            exports_1("C7", C7 = Object.freeze([2, 6]));
            exports_1("C8", C8 = Object.freeze([2, 7]));
            exports_1("D1", D1 = Object.freeze([3, 0]));
            exports_1("D2", D2 = Object.freeze([3, 1]));
            exports_1("D3", D3 = Object.freeze([3, 2]));
            exports_1("D4", D4 = Object.freeze([3, 3]));
            exports_1("D5", D5 = Object.freeze([3, 4]));
            exports_1("D6", D6 = Object.freeze([3, 5]));
            exports_1("D7", D7 = Object.freeze([3, 6]));
            exports_1("D8", D8 = Object.freeze([3, 7]));
            exports_1("E1", E1 = Object.freeze([4, 0]));
            exports_1("E2", E2 = Object.freeze([4, 1]));
            exports_1("E3", E3 = Object.freeze([4, 2]));
            exports_1("E4", E4 = Object.freeze([4, 3]));
            exports_1("E5", E5 = Object.freeze([4, 4]));
            exports_1("E6", E6 = Object.freeze([4, 5]));
            exports_1("E7", E7 = Object.freeze([4, 6]));
            exports_1("E8", E8 = Object.freeze([4, 7]));
            exports_1("F1", F1 = Object.freeze([5, 0]));
            exports_1("F2", F2 = Object.freeze([5, 1]));
            exports_1("F3", F3 = Object.freeze([5, 2]));
            exports_1("F4", F4 = Object.freeze([5, 3]));
            exports_1("F5", F5 = Object.freeze([5, 4]));
            exports_1("F6", F6 = Object.freeze([5, 5]));
            exports_1("F7", F7 = Object.freeze([5, 6]));
            exports_1("F8", F8 = Object.freeze([5, 7]));
            exports_1("G1", G1 = Object.freeze([6, 0]));
            exports_1("G2", G2 = Object.freeze([6, 1]));
            exports_1("G3", G3 = Object.freeze([6, 2]));
            exports_1("G4", G4 = Object.freeze([6, 3]));
            exports_1("G5", G5 = Object.freeze([6, 4]));
            exports_1("G6", G6 = Object.freeze([6, 5]));
            exports_1("G7", G7 = Object.freeze([6, 6]));
            exports_1("G8", G8 = Object.freeze([6, 7]));
            exports_1("H1", H1 = Object.freeze([7, 0]));
            exports_1("H2", H2 = Object.freeze([7, 1]));
            exports_1("H3", H3 = Object.freeze([7, 2]));
            exports_1("H4", H4 = Object.freeze([7, 3]));
            exports_1("H5", H5 = Object.freeze([7, 4]));
            exports_1("H6", H6 = Object.freeze([7, 5]));
            exports_1("H7", H7 = Object.freeze([7, 6]));
            exports_1("H8", H8 = Object.freeze([7, 7]));
        }
    };
});
//# sourceMappingURL=algebraic.js.map