var _a;
var BLACK = 'Black';
var WHITE = 'White';
var KING = 'King';
var QUEEN = 'Queen';
var ROOK = 'Rook';
var KNIGHT = 'Knight';
var BISHOP = 'Bishop';
var PAWN = 'Pawn';
var WK = WHITE + " " + KING;
var WQ = WHITE + " " + QUEEN;
var WR = WHITE + " " + ROOK;
var WN = WHITE + " " + KNIGHT;
var WB = WHITE + " " + BISHOP;
var WP = WHITE + " " + PAWN;
var BK = BLACK + " " + KING;
var BQ = BLACK + " " + QUEEN;
var BR = BLACK + " " + ROOK;
var BN = BLACK + " " + KNIGHT;
var BB = BLACK + " " + BISHOP;
var BP = BLACK + " " + PAWN;
var __ = null;
var EMPTY = __;
var ALL_PIECES = Object.freeze(new Set([BK, BQ, BR, BN, BB, BP, WK, WQ, WR, WN, WB, WP]));
var BLACK_PIECES = Object.freeze(new Set([BK, BQ, BR, BN, BB, BP]));
var WHITE_PIECES = Object.freeze(new Set([WK, WQ, WR, WN, WB, WP]));
var unicodeSymbols = (_a = {},
    _a[WK] = '♔',
    _a[WQ] = '♕',
    _a[WR] = '♖',
    _a[WB] = '♗',
    _a[WN] = '♘',
    _a[WP] = '♙',
    _a[BK] = '♚',
    _a[BQ] = '♛',
    _a[BR] = '♜',
    _a[BB] = '♝',
    _a[BN] = '♞',
    _a[BP] = '♟',
    _a[__] = ' ',
    _a);
//# sourceMappingURL=piecesNew.js.map