export type Piece = 
     | 'WhiteKing' 
     | 'WhiteQueen' 
     | 'WhiteRook' 
     | 'WhiteKnight' 
     | 'WhiteBishop' 
     | 'WhitePawn' 
     | 'BlackKing' 
     | 'BlackQueen' 
     | 'BlackRook' 
     | 'BlackKnight' 
     | 'BlackBishop' 
     | 'BlackPawn' 