export type Piece = 
     | 'White King' 
     | 'White Queen' 
     | 'White Rook' 
     | 'White Knight' 
     | 'White Bishop' 
     | 'White Pawn' 
     | 'Black King' 
     | 'Black Queen' 
     | 'Black Rook' 
     | 'Black Knight' 
     | 'Black Bishop' 
     | 'Black Pawn' 