declare enum Piece {
    WK = 'White King', 
    WhiteKing = 'White King', 
    WQ = 'White Queen', 
    WhiteQueen = 'White Queen', 
    WR = 'White Rook', 
    WhiteRook = 'White Rook', 
    WN = 'White Knight', 
    WhiteKnight = 'White Knight', 
    WB = 'White Bishop', 
    WhiteBishop = 'White Bishop', 
    WP = 'White Pawn', 
    WhitePawn = 'White Pawn', 
    BK = 'Black King', 
    BlackKing = 'Black King', 
    BQ = 'Black Queen', 
    BlackQueen = 'Black Queen', 
    BR = 'Black Rook', 
    BlackRook = 'Black Rook', 
    BN = 'Black Knight', 
    BlackKnight = 'Black Knight', 
    BB = 'Black Bishop', 
    BlackBishop = 'Black Bishop', 
    BP = 'Black Pawn',
    BlackPawn = 'Black Pawn',
    
    __ = '',
    Empty = ''
}