// export const enum Piece {
//     King = 'King',
//     Queen = 'Queen',
//     Rook = 'Rook',
//     Knight = 'Knight',
//     Bishop = 'Bishop',
//     Pawn = 'Pawn',
//     WK = 'White King', 
//     WQ = 'White Queen', 
//     WR = 'White Rook', 
//     WN = 'White Knight', 
//     WB = 'White Bishop', 
//     WP = 'White Pawn', 
//     BK = 'Black King', 
//     BQ = 'Black Queen', 
//     BR = 'Black Rook', 
//     BN = 'Black Knight', 
//     BB = 'Black Bishop', 
//     BP = 'Black Pawn',
//     __ = '',
//     Empty = ''
// }